# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BGPCapacityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(help_text='测试用例ID')),
                ('adjacency_status', models.CharField(default='-1', help_text='邻居建立状态', max_length=100, null=True)),
                ('router_status', models.CharField(default='-1', help_text='路由发送状态', max_length=100, null=True)),
                ('traffics_tatus', models.CharField(default='-1', help_text='验证流量发送状态', max_length=100, null=True)),
                ('router_traffic', models.CharField(default='-1', help_text='正常流量测试结果', max_length=100, null=True)),
                ('blackhole_traffic', models.CharField(default='-1', help_text='黑洞流量测试结果', max_length=100, null=True)),
                ('add_time', models.IntegerField(default='-1', help_text='添加时间', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ISISCapacityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(help_text='测试用例ID')),
                ('adjacency_status', models.CharField(default='-1', help_text='邻居建立状态', max_length=100, null=True)),
                ('router_status', models.CharField(default='-1', help_text='路由发送状态', max_length=100, null=True)),
                ('traffics_tatus', models.CharField(default='-1', help_text='验证流量发送状态', max_length=100, null=True)),
                ('router_traffic', models.CharField(default='-1', help_text='正常流量测试结果', max_length=100, null=True)),
                ('blackhole_traffic', models.CharField(default='-1', help_text='黑洞流量测试结果', max_length=100, null=True)),
                ('add_time', models.IntegerField(default='-1', help_text='添加时间', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='testcasestate',
            name='set_host_num',
            field=models.CharField(blank=True, default='-1', help_text='邻居书目', max_length=100),
        ),
        migrations.AddField(
            model_name='testcasestate',
            name='set_router_learning_time',
            field=models.CharField(blank=True, default='-1', help_text='路由学习时间', max_length=100),
        ),
        migrations.AddField(
            model_name='testcasestate',
            name='set_router_num',
            field=models.CharField(blank=True, default='-1', help_text='路由容量', max_length=100),
        ),
        migrations.AlterField(
            model_name='testcasestate',
            name='set_flow',
            field=models.CharField(blank=True, default='-1', help_text='测试流量', max_length=100),
        ),
        migrations.AlterField(
            model_name='testcasestate',
            name='set_online_rate',
            field=models.CharField(blank=True, default='-1', help_text='上线速率', max_length=100),
        ),
        migrations.AlterField(
            model_name='testcasestate',
            name='set_session',
            field=models.IntegerField(blank=True, default='-1', help_text='测试Session数'),
        ),
    ]
