# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0002_auto_20170828_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestate',
            name='set_host_num',
            field=models.CharField(blank=True, default='-1', help_text='邻居数目', max_length=100),
        ),
    ]
