# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0003_auto_20170828_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bgpcapacitytest',
            old_name='traffics_tatus',
            new_name='traffic_status',
        ),
        migrations.RenameField(
            model_name='isiscapacitytest',
            old_name='traffics_tatus',
            new_name='traffic_status',
        ),
    ]
