# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosite', '0005_auto_20170829_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestate',
            name='set_flow',
            field=models.CharField(blank=True, default='-1', help_text='测试流量', max_length=100),
        ),
        migrations.AlterField(
            model_name='testcasestate',
            name='set_host_num',
            field=models.CharField(blank=True, default='-1', help_text='邻居数目', max_length=100),
        ),
        migrations.AlterField(
            model_name='testcasestate',
            name='set_online_rate',
            field=models.CharField(blank=True, default='-1', help_text='上线速率', max_length=100),
        ),
        migrations.AlterField(
            model_name='testcasestate',
            name='set_router_learning_time',
            field=models.CharField(blank=True, default='-1', help_text='路由学习时间', max_length=100),
        ),
        migrations.AlterField(
            model_name='testcasestate',
            name='set_router_num',
            field=models.CharField(blank=True, default='-1', help_text='路由容量', max_length=100),
        ),
        migrations.AlterField(
            model_name='testcasestate',
            name='set_session',
            field=models.IntegerField(blank=True, default='-1', help_text='测试Session数'),
        ),
    ]
